# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Missatge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=250)),
                ('data_lectura', models.DateTimeField()),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discos.Oferta_disc')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localitat', models.CharField(max_length=50)),
                ('CP', models.IntegerField()),
                ('valoracio', models.IntegerField()),
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='missatge',
            name='msm_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missatges_enviats', to='usuaris.Perfil'),
        ),
        migrations.AddField(
            model_name='missatge',
            name='msm_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missatges_rebuts', to='usuaris.Perfil'),
        ),
    ]
