# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cognom',
            field=models.CharField(default='', editable=False, max_length=125),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nom',
            field=models.CharField(default='', editable=False, max_length=125),
        ),
        migrations.AddField(
            model_name='perfil',
            name='password',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='username',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='CP',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='valoracio',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
