# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_auto_20170220_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cognom',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='password',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='username',
        ),
    ]
