# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0003_auto_20170220_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, upload_to='perfil'),
        ),
    ]
