# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0004_perfil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, upload_to='perfils'),
        ),
    ]
