# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0005_auto_20170224_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missatge',
            name='data_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
