# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0006_auto_20170301_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missatge',
            name='data_lectura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
