# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_auto_20170220_1522'),
        ('discos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta_disc',
            name='usuari_comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuari_comprador', to='usuaris.Perfil'),
        ),
        migrations.AddField(
            model_name='oferta_disc',
            name='usuari_venedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuari_venedor', to='usuaris.Perfil'),
        ),
    ]
