# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0002_auto_20170220_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_disc',
            name='usuari_comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discos_comprats', to='usuaris.Perfil'),
        ),
        migrations.AlterField(
            model_name='oferta_disc',
            name='usuari_venedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discos_oferta', to='usuaris.Perfil'),
        ),
    ]
