# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0005_auto_20170222_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_disc',
            name='data_pujada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
