# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0006_auto_20170222_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_disc',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
